[package]
name = "pagegraph"
version = "0.1.0"
description = "Rust library for analyzing PageGraph files"
license = "MPL-2.0"
authors = ["Anton Lazarev <alazarev@brave.com>"]
edition = "2018"
readme = "../README.md"

[dependencies]
xml-rs = "^ 0.8"
petgraph = "^0.6.3"
adblock = "^ 0.2"
url = "^ 2.1"
addr = "^ 0.2"
serde = { version = "^ 1.0", features = ["derive"], optional = true }

[features]
default = [ "serde" ]
